### ISSUE TITLE
关于keras GAN 代码的问题

### ISSUE THREAD

**Issue by qinxie** [bojone/gan#1]
您好， 非常感谢您共享的代码。 我看了您关于Gan的keras代码，有一个地方不理解。

为什么d_train_model 的expected target value is None.  我不理解。非常感谢您的解答。

谢谢！

**Comment by qinxie** [comment]
您好，我理解了。您的代码中，自定义了loss。 我只能理解为什么在这种情况下expected target value is None。 我表达不出来。

**Comment by bojone** [comment]
因为有些场景下其实不需要y标签，比如自编码器。这种情况下，只要你的loss不包含y_true，它就可以不定义y输入，然后fit的时候的y就可以设为None

**Comment by qinxie** [comment]
非常感谢！确实是这样的。我修改了loss方法， 当使用keras自带的binary_crossentropy作为loss的时候，确实需要y_ture作为expected target。 因为在keras计算binary_crossentropy的时候是需要标签的， 所以train_on_batch的时候，也是需要y_target。 您的代码里面，自定义的d_loss和 g_loss, 在对抗训练的过程中，就在收敛。

自编码器不需要标签。但是，自编码器里面好像需要target， 这个我没有仔细看过。我做了一个自编码的作为generate的小代码， generate和input相似的分布，这里target 虽然不是y_true, 但是是有target的， 这里的target和input一样。 

非常感谢您的解答。关于自编码不需要标签的场景， 这个也很有意思，我想下去在看。

**Comment by bojone** [comment]
这里的y标签，指的是额外的监督输入，不一定就是类别信息。比如自编码器，可以这样写

```
x_in = Input(shape=(100,))
x = x_in

x = encoder(x)
x = decoder(x)

model = Model(x_in, x)
model.add_loss(K.mean((x - x_in)**2))
model.compile(optimizer='adam')

model.fit(x_train, None, epochs=10)
```

**Comment by qinxie** [comment]
YES！不好意思，是我没有理解您刚才的意思。是的，您的代码就是我刚才想表达的意思。“额外的监督输入”，我第一次听到这样的解释，感觉很贴切。

非常感谢！

**Comment by bojone** [comment]
OK，有问题欢迎再交流。
